# Generated by Django 4.2.12 on 2024-09-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
